# Generated by Django 5.2.15 on 2026-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelroute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('city_normalized', models.CharField(db_index=True, max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('display_name', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city_normalized'], name='fuelroute_c_state_f74c7b_idx')],
                'constraints': [models.UniqueConstraint(fields=('state', 'city_normalized'), name='unique_state_city')],
            },
        ),
    ]
